### PR TITLE
[triggers/cmd] clean up ioutil for new go version

### PR DESCRIPTION
**Pull request by my-git9**
# Changes
Clean up ioutil for new go version in dirctory triggers/cmd
Ref: https://github.com/tektoncd/triggers/issues/1495

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Review by dibyom — APPROVED** [review]

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by khrm** [comment]
I have merged this pr to my pr: https://github.com/tektoncd/triggers/pull/1534

**Pull request closed without merging**
