### PR TITLE
Update triggers, community and cli reference to use main…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

… instead of master.

/cc @afrittoli @bobcatfish 
/cc @tektoncd/triggers-maintainers @tektoncd/triggers-collaborators 

/hold
/kind misc

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by vdemeester** [comment]
```
        {"level":"error","ts":"2021-03-09T20:52:37.373Z","logger":"webhook-triggers.ConfigMapWebhook","caller":"controller/controller.go:540","msg":"Reconcile error","duration":0.000051573,"error":"secret \"triggers-webhook-certs\" is missing \"ca-cert.pem\" key","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:523\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/controller/controller.go:460"}
```

**Comment by vdemeester** [comment]
```
default            13m         Warning   InspectFailed                  pod/gh-validate-6fb777c8f7-xt9ct                                           Failed to apply default image tag "ko://github.com/tektoncd/triggers/examples/event-interceptors": couldn't parse image reference "ko://github.com/tektoncd/triggers/examples/event-interceptors": invalid reference format
default            13m         Warning   Failed                         pod/gh-validate-6fb777c8f7-xt9ct                                           Error: InvalidImageName
```

🤔

**Comment by savitaashture** [comment]
> ```
> default            13m         Warning   InspectFailed                  pod/gh-validate-6fb777c8f7-xt9ct                                           Failed to apply default image tag "ko://github.com/tektoncd/triggers/examples/event-interceptors": couldn't parse image reference "ko://github.com/tektoncd/triggers/examples/event-interceptors": invalid reference format
> default            13m         Warning   Failed                         pod/gh-validate-6fb777c8f7-xt9ct                                           Error: InvalidImageName
> ```

Strange!! I m able to make it work locally

**Comment by vdemeester** [comment]
@savitaashture yeah I don't get why it fails on the CI 🤔

**Pull request merged**
