### PR TITLE
Update examples to use both old and new syntax

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

Addresses #1023 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by dibyom** [comment]
@jmcshane Is this what you were looking for? 

We also have https://github.com/tektoncd/triggers/issues/1009 which will let us do this automatically for any new or existing triggers

**Review by savitaashture — APPROVED** [review]
/lgtm

**Pull request merged**
