### PR TITLE
Fix typo in README.md of getting started

### PR DESCRIPTION
**Pull request by hnts**
# Changes
I fixed typo in README.md of getting-started.

mimimum -> minimum

Please review this pull request :)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by dibyom** [comment]
Thank you @hnts would you mind signing the CLA

**Comment by hnts** [comment]
@dibyom 
I signed the CLA!

**Comment by savitaashture** [comment]
Thank you @hnts 

/lgtm

**Pull request merged**
