### PR TITLE
Update the TriggerTemplate in Examples to Beta API

### PR DESCRIPTION
**Pull request by khrm**
Update the TriggerTemplate in Examples to refer to beta APIs of Pipelines

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by dibyom** [comment]
> {"level":"error","ts":"2022-07-26T20:01:49.331Z","logger":"eventlistener","caller":"sink/sink.go:524","msg":"problem creating obj: &errors.errorString{s:\"couldn't create resource with group version kind \\\"tekton.dev/v1beta1, Resource=taskruns\\\": admission webhook \\\"webhook.pipeline.tekton.dev\\\" denied the request: mutation failed: cannot decode incoming new object: json: unknown field \\\"inputs\\\"\"}","eventlistener":"bitbucket-listener","namespace":"default","/triggers-eventid":"84d36cd5-18d7-45cb-b203-1914aa204c65","eventlistenerUID":"00d379bc-bbee-4fe0-b632-592fb9944845","/triggers-eventid":"84d36cd5-18d7-45cb-b203-1914aa204c65","/trigger":"bitbucket-triggers","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.CreateResources\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:524\ngithub.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:412\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:196"}

**Comment by dibyom** [comment]
@khrm Thanks! I think we also need to update the template itself since the syntax has changed between v1alpha1 and v1beta1

**Comment by khrm** [comment]
Now, it's failing due to knative. 

```Error from server (InternalError): error when creating "https://github.com/knative/net-kourier/releases/download/v0.26.0/kourier.yaml": Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": failed to call webhook: Post "[https://webhook.knative-serving.svc:443/config-validation?timeout=10s](https://webhook.knative-serving.svc/config-validation?timeout=10s)": no endpoints available for service "webhook"```

/test pull-tekton-triggers-integration-tests

**Review by dibyom — APPROVED** [review]

**Pull request merged**
