### PR TITLE
Fixes for running on k8s 1.23 and  restricted PodSecurityAdmission level

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

There are two commits which are both required for Triggers to work with Pipelines v0.41 which requires Kubernetes 1.23.

1. [Use cos_containerd gke image for e2e tests](https://github.com/tektoncd/triggers/pull/1477/commits/f2e5f0ecfc101344c735509b8ff6e06dd986ab86)

This commit updates our plumbing dependency to pull in tektoncd/plumbing#1251 which updates the GKE image to cos_containerd. The older cos image is no longer supported as of GKE v1.23.

Part of #1475 

2. [Replace PodSecurityPolicy with PodSecurityAdmission](https://github.com/tektoncd/triggers/pull/1477/commits/c0f697dcd711d6250e8c02dd661455f1232c6097) 

This commit drops the Triggers PodSecurityPolicy since its deprecated and is
going to be removed in Kubernetes 1.25 in favor of PodSecurityAdmission.

In addition, it adds the `securityContext` required for the "restricted"
PodSecurityAdmission levels. These changes are necessary for Triggers to work
with Pipelines v0.41 and higher because https://github.com/tektoncd/pipeline/pull/5652  started
enforcing the restricted pod security level for all pods in the
`tekton-pipelines` namespace (which includes the triggers controller, webhook,
and core interceptor deployments).

Fixes https://github.com/tektoncd/triggers/issues/1447 and required for https://github.com/tektoncd/triggers/issues/1475

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
action required:  If using Kubernetes 1.22, set PodSecurity flag to true to enforce a restricted pod security level in Tekton namespaces. See https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-graduated-or-deprecated-features for more information.

E2E tests now use cos_containerd image instead of the unsupported cos image
```

### CODE REVIEW

**Comment by dibyom** [comment]
Running into PSP issues:


```
tekton-pipelines             26m         Warning   FailedGetResourceMetric   horizontalpodautoscaler/tekton-pipelines-webhook                     no recommendation
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-g4gpb" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-tkv9h" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-9fd8q" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-4sk4w" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-8c9bx" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-x9ljg" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-4gfkw" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-w2rqv" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-74px6" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             14m         Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     (combined from similar events): Error creating: pods "tekton-triggers-controller-7887549bc5-htzd7" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             3m50s       Warning   FailedCreate              replicaset/tekton-triggers-controller-7887549bc5                     Error creating: pods "tekton-triggers-controller-7887549bc5-gr8gh" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Normal    ScalingReplicaSet         deployment/tekton-triggers-controller                                Scaled up replica set tekton-triggers-controller-7887549bc5 to 1
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-r9t88" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-hdsgb" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-d5frk" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-dmbs7" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-xhwcn" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-pjlxn" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-fcthd" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-bpvpb" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-xlvf7" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             14m         Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              (combined from similar events): Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-xtxz6" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             3m30s       Warning   FailedCreate              replicaset/tekton-triggers-core-interceptors-5cdb877c4b              Error creating: pods "tekton-triggers-core-interceptors-5cdb877c4b-4s9h9" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "tekton-triggers-core-interceptors" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "tekton-triggers-core-interceptors" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "tekton-triggers-core-interceptors" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Normal    ScalingReplicaSet         deployment/tekton-triggers-core-interceptors                         Scaled up replica set tekton-triggers-core-interceptors-5cdb877c4b to 1
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-7dgsb" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-ghl4p" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-2w94v" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-wlwgs" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-nblcd" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-84lpz" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-rfjxw" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-j2tv6" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             25m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-xcnfw" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             14m         Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        (combined from similar events): Error creating: pods "tekton-triggers-webhook-7464568dfc-wrdkf" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
tekton-pipelines             3m50s       Warning   FailedCreate              replicaset/tekton-triggers-webhook-7464568dfc                        Error creating: pods "tekton-triggers-webhook-7464568dfc-vfgrz" is forbidden: violates PodSecurity "restricted:latest": unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Review by savitaashture — APPROVED** [review]

**Review by savitaashture — COMMENTED** [review]
:tada: 

/lgtm

**Comment by seunggs** [comment]
I apologize if this is the wrong place to provide feedback on this ticket, but I'm still getting this error on k8s v1.24, pipelines v0.42 and triggers v0.22 (I can confirm that `securityContext` fix is present in `tekton-triggers-controller` and `-webhook`):

```
Warning  FailedCreate  47s (x7 over 3m29s)  replicaset-controller  (combined from similar events): Error creating: pods "el-pulumi-el-8bc4bf7-nxznb" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "event-listener" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "event-listener" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "event-listener" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

**Comment by dibyom** [comment]
@seunggs are you running an eventlistener in the tekton-pipelines namespace?

**Comment by dcshiman** [comment]
> @seunggs are you running an eventlistener in the tekton-pipelines namespace?

I'm facing the same issue, running in `tekton-pipelines` namespace

**Comment by seunggs** [comment]
@dibyom Yes, `tekton-pipelines` namespace

**Comment by dibyom** [comment]
ok - a quick workaround will be to run your EL in a different namespace till we add a fix

**Comment by seunggs** [comment]
@dibyom thanks - I've just changed the tekton-pipelines namespace setting: `enforce` -> `warning` for now and I was able to create the `el`

**Pull request merged**
