### PR TITLE
Bump knative/pkg to 1.11

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes

Bump knative/pkg to the latest, 1.11

This also updates the min kubernetes version to 1.25.

Bumped knative pkg version as part of this issue https://github.com/tektoncd/triggers/issues/1628

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
@savitaashture We shouldn't update knative directly. We should only bump the pipeline and it will bump the knative.
/hold

**Comment by khrm** [comment]
Elaborating that:

Doing this can cause a potential mismatch for the minimum version of k8s needed between `Pipelines` and `Triggers`.

Similarly, we never update the k8s API in `Pipelines`. They come from `Knative`.

**Comment by savitaashture** [comment]
> Doing this can cause a potential mismatch for the minimum version of k8s needed between `Pipelines` and `Triggers`.

I think with this update both pipeline and Triggers will have kubernetes version as 1.25.

**Comment by savitaashture** [comment]
> @savitaashture We shouldn't update knative directly. We should only bump the pipeline and it will bump the knative.

Right bumping to 0.50.1 will bump knative version to https://github.com/tektoncd/pipeline/blob/release-v0.50.x/go.mod#L37 

But i referred @vdemeester PR https://github.com/tektoncd/pipeline/pull/6975 related to knative pkg issue

**Comment by khrm** [comment]
Yes. In this case, doing this will cause the `Triggers` min  k8s version to be 1.25 which is higher than `Pipelines` v0.50.

BTW, #1628 is resolved by https://github.com/tektoncd/triggers/commit/c366270ccd9c6ad118eec4ff791cb360bdbf492f which will be done in the v0.25 release. That's why I assigned you.

**Comment by khrm** [comment]
So I think we can close this?

**Comment by savitaashture** [comment]
> So I think we can close this?

Yes

**Pull request closed without merging**
