### PR TITLE
Fix GitHub and GitLab capitalization

### PR DESCRIPTION
**Pull request by Alan-Cha**
# Changes

Fix the capitalization of "GitHub" and "GitLab" in documentation and in comments.

### CODE REVIEW

**Comment by dibyom** [comment]
Thanks @Alan-Cha 

Could you remove the changes made to the files under the `vendor/` directory? Those are third party dependencies and so should not be changed (as a script will overwrite them). Fixing that should also fix the failing build test.

**Comment by Alan-Cha** [comment]
@dibyom I believe I removed the changes under the `vendor/` directory. Please let me know if there is anything else you need!

**Review by wlynch — APPROVED** [review]
/lgtm

Thanks for the contribution! 🥳

**Pull request merged**
