### PR TITLE
fix typo for release and interceptors name

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]
Do we have to re-do any of the previous releases for this? I guess we could just rename the release files in the bucket

**Comment by savitaashture** [comment]
> Do we have to re-do any of the previous releases for this? I guess we could just rename the release files in the bucket

@dibyom No we don't have to because the typo is in result display so it doesn't effect functionality as such
Only thing if someone copy URL from displayed results they get 404 error that is the reason corrected typo.

**Comment by nikhil-thomas** [comment]
changes looks good.
@dibyom the filenames/links in gcp bucket and in github release are what we want.

These typos result in printing wrong urls in release-pipeline-results.

**Pull request merged**
