### PR TITLE
Removing deprecated fields

### LINKED ISSUE #904: Remove Deprecate fields PodTemplate and ServiceType
PodTemplate and ServiceType are deprecated and need to be removed in a future release.

### PR DESCRIPTION
**Pull request by jmcshane**
# Changes

Closes #904

This PR removes the deprecated ServiceType and PodTemplate fields from the EventListener Spec

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Removes deprecated API fields from EventListener spec
```

### CODE REVIEW

**Comment by jmcshane** [comment]
The reduction in test coverage in the defaults package is due to the removal of code that was covered at 100% (higher than the rest of the file). Any other test changes made in this PR would be unrelated to the removal of the deprecated fields.

**Comment by jmcshane** [comment]
The only thing I see left here is if we want to call out the `kubernetesResource.serviceType` field explicitly as a way to expose event listener in the `exposing-eventlisteners.md` document. This document did not have the deprecated `ServiceType` field called out, but it was called out in a couple of the examples. Besides that, this was a straightforward removal of the two removed fields.

**Comment by dibyom** [comment]
This LGTM. We should decide which release we are intending to remove these fields.

**Comment by dibyom** [comment]
I think this can make it to the v0.14 release.

Just needs a rebase and then good to go.
/approve

**Comment by jmcshane** [comment]
this PR should be good to go now for the release. everything has been cleaned up.

Should we write a document specific to migrating to this version given the removal of these fields?

**Pull request merged**
