### PR TITLE
Fix go1.19 related codegen issues

### PR DESCRIPTION
**Pull request by khrm**
Updated code by running ./hack/codegen.sh with go1.19. Needed for passing tests.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind misc

**Comment by khrm** [comment]
We are facing a chicken and egg issue. I would have to add those by pr by @my-git9 here.

**Comment by khrm** [comment]
@my-git9 I have added your commits here. https://github.com/tektoncd/triggers/pull/1534
Because tests were failing and we needed those changes along with generated code.

**Review by dibyom — APPROVED** [review]
/lgtm

**Comment by khrm** [comment]
Fixes #1495  also

**Pull request merged**
