### PR TITLE
Add v1beta1 specific example in e2e-tests

### PR DESCRIPTION
**Pull request by khrm**
In addition to common examples in v1alpha1 and v1beta1, changed
the script to add v1beta1 specific examples.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]
/lgtm

**Comment by dibyom** [comment]
> /home/prow/go/src/github.com/tektoncd/triggers/test/e2e-tests-examples.sh: line 178: examples_alpha: unbound variable

**Comment by khrm** [comment]
Now we are failing due to this:
```Error from server (InternalError): Internal error occurred: failed calling webhook "config.webhook.serving.knative.dev": Post "https://webhook.knative-serving.svc:443/config-validation?timeout=10s": no endpoints available for service "webhook"
```

**Comment by dibyom** [comment]
```
+ folder=/home/prow/go/src/github.com/tektoncd/triggers/examples/v1alpha1/examples_v1alpha1
++ sort
++ find /home/prow/go/src/github.com/tektoncd/triggers/examples/v1alpha1/examples_v1alpha1/ -name '*.yaml'
find: '/home/prow/go/src/github.com/tektoncd/triggers/examples/v1alpha1/examples_v1alpha1/': No such file or directory
+ yaml_files=
+ err 'failed to find files'
+ echo

+ echo 'ERROR: Example v1alpha1/examples_v1alpha1: failed to find files'
ERROR: Example v1alpha1/examples_v1alpha1: failed to find files
+ echo
```

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
