### PR TITLE
Begin to address metrics in namespaced eventlistener

### LINKED ISSUE #736: FR: Metrics for EventListener
# Expected Behavior

The EventListener sink should be instrumented to emit metrics in order to help with monitoring and observability. As an example, knowing the number of triggers processed would be very helpful in debugging #687 

# Actual Behavior

The EventListener does not emit any metrics today. One workaround is to read/parse the log messages instead.

# Additional Info
Some ideas for metrics to add would be a counter for the number of total requests processed by the listener, a counter for per trigger invocations, gauge for number of concurrent requests, avg/95 percentile request duration etc.

The EL sink should be instrumented to emit metrics at a documented metrics HTTP port. Users can then use their monitoring tools to scrape metrics and build dashboards. 

One option would be to use something like the Prometheus client or OpenCensus to instrument -- this should add some default metrics in addition to any custom ones we define.
https://prometheus.io/docs/guides/go-application/
https://opencensus.io/guides/http/go/net_http/

(We should probably open a TEP with a design first before implementing this.)

/kind feature

### PR DESCRIPTION
**Pull request by jmcshane**
# Changes

Adding metrics endpoint for eventlistener deployment

Closes #736 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Add metrics for eventlistener deployment
```

### CODE REVIEW

**Comment by dibyom** [comment]
```
   {"level":"panic","ts":1614360420.79392,"logger":"fallback","caller":"client/client.go:46","msg":"Unable to fetch k8s.io/client-go/kubernetes.Interface from context. This context is not the application context (which is typically given to constructors via sharedmain).","stacktrace":"knative.dev/pkg/client/injection/kube/client.Get\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/client/injection/kube/client/client.go:46\nknative.dev/pkg/injection/sharedmain.SetupConfigMapWatchOrDie\n\tknative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/injection/sharedmain/main.go:294\nmain.main\n\tgithub.com/tektoncd/triggers/cmd/eventlistenersink/main.go:71\nruntime.main\n\truntime/proc.go:204"}
        panic: Unable to fetch k8s.io/client-go/kubernetes.Interface from context. This context is not the application context (which is typically given to constructors via sharedmain).
        
        goroutine 1 [running]:
        go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000233440, 0x0, 0x0, 0x0)
        	go.uber.org/zap@v1.16.0/zapcore/entry.go:234 +0x585
        go.uber.org/zap.(*SugaredLogger).log(0xc00000e6d0, 0x1c4c704, 0x0, 0x0, 0xc00080f9f8, 0x1, 0x1, 0x0, 0x0, 0x0)
        	go.uber.org/zap@v1.16.0/sugar.go:234 +0xf6
        go.uber.org/zap.(*SugaredLogger).Panic(...)
        	go.uber.org/zap@v1.16.0/sugar.go:123
        knative.dev/pkg/client/injection/kube/client.Get(0x22263e0, 0xc000486468, 0x0, 0x0)
        	knative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/client/injection/kube/client/client.go:46 +0x285
        knative.dev/pkg/injection/sharedmain.SetupConfigMapWatchOrDie(0x22263e0, 0xc000486468, 0xc000486820, 0x17)
        	knative.dev/pkg@v0.0.0-20210130001831-ca02ef752ac6/injection/sharedmain/main.go:294 +0x50
        main.main()
        	github.com/tektoncd/triggers/cmd/eventlistenersink/main.go:71 +0x345
        
```

**Comment by jmcshane** [comment]
Ah shoot, i need to get a more complete integration test environment stood up rather than relying on the unit tests. im going to need to be more careful about my interaction with `sharedmain`

**Comment by dibyom** [comment]
> Ah shoot, i need to get a more complete integration test environment stood up rather than relying on the unit tests. im going to need to be more careful about my interaction with sharedmain

I've been using minikube for my setup. Works pretty well!

And yeah I think using sharedmain outside the reconciler might be a bit of a challenge....it might be making assumptions that are not true.

**Comment by jmcshane** [comment]
We’ve got a kind setup that has worked well for testing the patches, the event listener is just a little harder because its spun up by the controller...

I’m a bit concerned with this reconcile loop being backwards compatible with an existing EL upgrading to this patch, I’ll definitely try to address the upgrade situation in my local setup

**Comment by jmcshane** [comment]
no custom metrics from event listener yet, im going to start with the basic HTTP request instrumentation for the sink handler

**Comment by jmcshane** [comment]
todos:

- [ ] unit tests in reconciler
- [ ] add/tag default HTTP metrics
- [ ] documentation for metrics server
- [ ] remove hardcoding prometheus port

This event listener works as is now, its changing the entrypoint just a bit, but overall a straightforward modification to sink.

**Comment by jmcshane** [comment]
So, ive seen this error a couple times in the integration tests (and once locally), where the eventlistener pod wasn't given access to the resources necessary to execute the handler loop:

```
        {"level":"error","ts":"2021-02-28T01:32:04.594Z","logger":"eventlistener","caller":"sink/sink.go:80","msg":"Error getting EventListener my-eventlistener in Namespace arrakis-s6n5d: eventlistener.triggers.tekton.dev \"my-eventlistener\" not found","knative.dev/controller":"eventlistener","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:80\ngithub.com/tektoncd/triggers/pkg/sink.NewMetricsRecorderInterceptor.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/metrics.go:85\ngithub.com/tektoncd/triggers/pkg/sink.MiddlewareHandlerFunc.Intercept.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/metrics.go:118\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2417\nnet/http.(*timeoutHandler).ServeHTTP.func1\n\tnet/http/server.go:3272"}
```

one thought here would be to resolve the eventlistener data outside of the handler loop so that these errors do not block HTTP requests

**Comment by jmcshane** [comment]
obviously i want to investigate the flakiness of these integration tests...but im having trouble nailing it down. i updated the test to allow retries (but didn't rebase yet so i can just clear that change back easily)

have any of the maintainers seen this happening in other PRs?

**Comment by jmcshane** [comment]
looks like what is happening is that the listers aren't updated (some of the time) with the updated triggerbinding or event listener. the eventlistener readiness probe could be updated for these tests with a delay period so it doesn't pass the readiness probe immediately.

the other options would be to delay the sending of the post HTTP request to the EL, as it seems to be an issue with syncing the listers when everything is created at once

**Comment by jmcshane** [comment]
Looking across some recent PRs, it looks like this has been a flaky test recently. What I see locally is that this is dependent on the Kube API server resources, if I have a bunch of pods running then it doesn't get the notification out in time to get this eventlistener spun up successfully.

Thinking about the consequences of a small delay here in the integration tests, I do wonder if it would make sense to block the HTTP server registration on retrieving the eventlistener record by the sink. I've discussed in #970 that the trigger pull and label selection is all done inside of a single HTTP request rather than as an outside control loop. If we could block eventlistener sink startup on the condition of retrieving the eventlistener object, then we could avoid this particular issue.

**Comment by dibyom** [comment]
> If we could block eventlistener sink startup on the condition of retrieving the eventlistener object, then we could avoid this particular issue.

Yeah that approach makes sense to me.

**Comment by jmcshane** [comment]
im going to write a separate PR to address that concern as it is not related specifically to metrics

**Comment by jmcshane** [comment]
Closing in favor of #1061

**Pull request closed without merging**
