### PR TITLE
Update TriggerBinding type to only have one event type

### PR DESCRIPTION
**Pull request by ncskier**
# Changes

- Remove Event type from the list of bindings in the TriggerBinding spec.
  - The EventListener can have multiple TriggerBindings, so each TriggerBinding having multiple events seems like overlapping functionality. So, with this PR each TriggerBinding will only have one event type.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by EliZucker** [comment]
If we do this then I propose something like what was mentioned in #55 . With this PR, TriggerBindings will not be reusable at all because of the single TriggerTemplate tied to it in its spec.

**Comment by ncskier** [comment]
@EliZucker My intention was only to tie each TriggerBinding to one event. I didn't mean to mess with the reusability of TriggerBindings. I just made an update; would this be a better change?

**Comment by vincent-pli** [comment]
If `TriggerBinding` only has one event type, have to put the `Condition/Router` to `EventListener`.

**Comment by ncskier** [comment]
@vincent-pli why would this mean the Condition/Router would have to go in the `EventListener`? The EventListener Pod can still use the Condition/Router info in the `TriggerBinding` to route events.

**Comment by vincent-pli** [comment]
@ncskier 
Based on this pr, the `TriggerBinding` will only has one event type, that's means if a `EventListener` want to handle a dozen of event type, it need refer to dozen of `TriggerBinding`.
if the `Condition/Router` is in the `TriggerBinding`, it need get all `TriggerBinding` from  k8s cluster and check them one by one to find the right one.

**Comment by ncskier** [comment]
@vincent-pli Yes, that is correct. At the moment I think that we should limit each `TriggerBinding` to supporting one event type, because this keeps the `TriggerBinding` resource from becoming too bloated & confusing. To address your technical concern about the `EventListener` needing to check each binding one-by-one, if I'm not mistaken, I think we can have the `EventListener` maintain an internal map of its `TriggerBinding`s' routing information, to reduce the time it takes to iterate over the bindings.

Also, unless we only allow the `EventListener` to use one `TriggerBinding`, then this iterating process is inevitable. This PR is intended to fix/simplify the overlapping nature of `EventListeners` having multiple `TriggerBindings`, and `TriggerBindings` also receiving multiple events. I think the best solution is to force each `TriggerBinding` to only receive one event type specified by the `Condition/Router` information.

**Comment by ncskier** [comment]
It looks like we're doing a bigger refactor of the `TriggerBinding` in PR https://github.com/tektoncd/triggers/pull/63, so I'm going to close this PR

**Pull request closed without merging**
