### PR TITLE
Bump CEL to v0.20.1

### PR DESCRIPTION
**Pull request by bigkevmcd**
# Changes

This registers the newest cel Extensions.

 * Lists
 * Sets
 * Maths

The docs are updated and the cel-eval tool has been updated to register the extensions.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [X] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

/kind cleanup

# Release Notes

```release-note
CEL interceptor updated to cel-go v0.20.1 and extensions for manipulating lists, sets and mathematical functions have been added.
```

### CODE REVIEW

**Comment by bigkevmcd** [comment]
@khrm Updated with the correct registrations.

**Review by khrm — COMMENTED** [review]
Please make changes in the test file also: https://github.com/tektoncd/triggers/blob/13242634b7d51141f4756ee514d1beb256c770e9/cmd/cel-eval/cmd/root_test.go#L10

**Review by khrm — COMMENTED** [review]
/approve

**Comment by khrm** [comment]
@savitaashture Let's merge this for v0.27.0

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
