### PR TITLE
Refactor interceptor main package

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes
Fixes: https://github.com/tektoncd/triggers/issues/1441

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by savitaashture** [comment]
> The following is the coverage report on the affected files. Say `/test pull-tekton-triggers-go-coverage` to re-run this coverage report
> 
> File	Old Coverage	New Coverage	Delta
> [pkg/interceptors/server/server.go](https://storage.cloud.google.com/tekton-prow/pr-logs/pull/tektoncd_triggers/1467/pull-tekton-triggers-go-coverage/1582733383719456768/artifacts/line-cov.html#file0)	77.7%	57.6%	-20.0

Coverage decreased because in code we are using 
```
secret, err := secretInformer.Get(ctx).Lister().Secrets(system.Namespace()).Get(os.Getenv(interceptorTLSSecretKey))
                        if err != nil {
                                logger.Errorf("failed to fetch secret %v", err)
                                return nil, nil
                        }
``` 
and from test even if create secret object informer won't able to get the data
because of that some parts of code is not covered

**Review by khrm — COMMENTED** [review]
/approve

**Comment by dibyom** [comment]
I think we can refactor the functions a bit and add some tests - we've had a few bugs around this behavior so its not ideal to have not tests for it.

For GetTLSData - we could use a fakesecretinformer + pass in namespace and secret name as arguments to the function
For UpdateCACertToClusterInterceptorCRD we can either extract the code under the go routine into its own function to test or use a fake clock

**Comment by savitaashture** [comment]
@dibyom PR is ready 
PTAL
Thank you

**Comment by dibyom** [comment]
Thank you!

**Pull request merged**
