### PR TITLE
Make TriggerBinding optional in EventListener.

### LINKED ISSUE #165: Make TriggerBindings optional for EventListeners
# Expected Behavior

Don't require a TriggerBinding for EventListeners. If it is not defined, assume there are no bindings.

# Actual Behavior

EventListener fails (not during creation, during runtime) with the error:

```
2019/10/10 19:31:03 Error getting TriggerBinding : resource name may not be empty
```

This error is visible in the event listener pod logs.

# Steps to Reproduce the Problem

Sample event listener (adapted from https://github.com/tektoncd/triggers/pull/162/commits/d9baa3bccbf3ab22b8c9849a5a0e2df8a8171514):

```
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cron-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cron-trig
      template:
        name: pipeline-template
      params:
      - name: message
        value: Hello from the Triggers EventListener!
      - name: gitrevision
        value: master
      - name: gitrepositoryurl
        value: https://github.com/tektoncd/triggers
```

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Currently if the TriggerBinding is omitted, it is unable to be
resolved and returns an error during event handling.

This loosens the constraint and makes a missing TriggerBinding a valid
value.

Resolves #165

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Allows EventListener triggers to be created without TriggerBindings set.
```

### CODE REVIEW

**Comment by khrm** [comment]
Won't it be a better pattern to make binding as pointer and check that for value? Like interceptor here: https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go#L70

**Comment by wlynch** [comment]
> Won't it be a better pattern to make binding as pointer and check that for value? Like interceptor here: https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go#L70

Done!

**Pull request merged**
