### PR TITLE
Redundant struct

### PR DESCRIPTION
**Pull request by khrm**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]
/lgtm

**Comment by dibyom** [comment]
/hold

look like this contains the yaml changes too

**Comment by khrm** [comment]
@dibyom Removed that yaml.

**Comment by khrm** [comment]
I think we can remove the hold here. @dibyom

**Comment by dibyom** [comment]
oops sorry
/hold cacnel

**Pull request merged**
