### PR TITLE
Replace cloudevents resource with task from hub

### LINKED ISSUE #1522: Replace cloud event resource usage
Use https://hub.tekton.dev/tekton/task/cloudevent to send the cloudevent (or maybe just get rid of it since its probably more complex than needed for a getting-started?)

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

Cloud events pipeline resource was removed from pipelines recently. Our E2E
tests run against the main branch of pipelines and that the getting-started
tutorial still uses this resource, our e2e tests have been failing.

Fixes #1522 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by dibyom** [comment]
@savitaashture @khrm please take a look. This should unblock the other PRs

**Review by savitaashture — APPROVED** [review]
/lgtm

**Pull request merged**
