### PR TITLE
Catch tabs vs spaces with gofmt presubmit linting

### PR DESCRIPTION
**Pull request by ncskier**
# Changes

Fixes issue https://github.com/tektoncd/triggers/issues/28.

- Update vendor plumbing repo to use gofmt presubmit linting
- Fix go files with inconsistent spacing

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by ncskier** [comment]
The pre-submit tests should fail, because there are currently files that have inconsistent spacing. 
/hold

**Comment by ncskier** [comment]
The tests look like they're working 👍 
/hold cancel

**Comment by EliZucker** [comment]
@vdemeester I actually don't think this is even being checked properly in pipelines. One of my pipeline PRs included a fix to make a random file match gofmt output, which I don't think would have been necessary if plumbing already verified that

**Comment by vdemeester** [comment]
@EliZucker yeah you are right it's not checked at all in `pipeline` (or most other tekton projects), hence my proposal to move it in `plumbing` :smiling_imp:

**Comment by ncskier** [comment]
@vdemeester I opened a PR in the plumbing repo https://github.com/tektoncd/plumbing/pull/49, although I'm not exactly sure where to put the code; let me know how it looks 😄 

I'll keep this PR open to update our `triggers` vendor & fix the files that will fail the new `gofmt` test.

**Comment by ncskier** [comment]
This PR is ready for another review. I've updated the description:

## Changes
- Update vendor plumbing repo to use gofmt presubmit linting
- Fix go files with inconsistent spacing

**Pull request merged**
