### PR TITLE
Fix Error by given linters during tests

### PR DESCRIPTION
**Pull request by khrm**
Fix error given by revive linter either by commenting if it can't be fixed or fixing the issue.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind misc

**Comment by khrm** [comment]
@dibyom Please merge this to resolve the latest CI issue with build test failure.

**Review by dibyom — APPROVED** [review]
/lgtm

**Pull request merged**
