### PR TITLE
Clarify bitbucket HMAC example

### PR DESCRIPTION
**Pull request by NissesSenap**
# Changes
Clarify bitbucket instruction on how to generate the X-Hub-Signature

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by NissesSenap** [comment]
@savitaashture as discussed on slack I created a PR

**Review by savitaashture — COMMENTED** [review]
@NissesSenap Thanks for the changes :slightly_smiling_face: 

Can you do same changes for Github related example here https://github.com/tektoncd/triggers/tree/master/examples/github 

otherwise Looks good to me

**Comment by NissesSenap** [comment]
I think i screwed up my squashing...
Have a look if the github one is okay as well and if you want I can redo the squash and do a force push

**Comment by dibyom** [comment]
> Have a look if the github one is okay as well and if you want I can redo the squash and do a force push

Yes, this looks great. Just needs a squash and we are good to go! Thanks!!

**Comment by NissesSenap** [comment]
Push force fixes everything :)

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
