### PR TITLE
Bump pipeline version v0.16.3

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by dibyom** [comment]
I think this also changes the minimum version of k8s we need to 1.16 or higher

**Comment by savitaashture** [comment]
> I think this also changes the minimum version of k8s we need to 1.16 or higher

yes using `v0.17.6` but i think because of knative pkg version change there is some changes in generated clients

**Comment by dibyom** [comment]
I think this version also adds leader election capability so we might have to call `Promote` in any tests that create a reconciler: 
https://github.com/tektoncd/pipeline/blob/master/pkg/reconciler/taskrun/taskrun_test.go#L294

**Comment by vdemeester** [comment]
@tektoncd/triggers-maintainers so in the future, it would be nice if each triggers release would  bump to the latest tektoncd/pipeline version available at that time :stuck_out_tongue:

**Comment by savitaashture** [comment]
Raised another PR tektoncd/triggers#767 and closing this because did lot of hacks and its becoming difficult to solve

/cc @dibyom

**Pull request closed without merging**
