### PR TITLE
Remove import of github.com/pkg/errors.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Remove import of github.com/pkg/errors.

This was accidentally pulled in by goimports in a885e77.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by wlynch** [comment]
> by goimports? interesting!
> /lgtm

Yeah it's because I used errors.Errorf, which does not exist in the base errors package. You can use fmt.Errorf or errors.New. So goimports then pulled in the next closest matching one (which worked because zap imports it so it's already vendored).

**Comment by dibyom** [comment]
@wlynch looks like you got linted :sweat_smile: 

> I0110 20:59:25.484] pkg/interceptors/webhook/webhook_test.go:116:3: S1023: redundant `return` statement (gosimple)
> I0110 20:59:25.485] 		return

**Comment by wlynch** [comment]
:man_facepalming: idk why that wasn't caught in the last PR

**Pull request merged**
