### PR TITLE
Interceptor SDK

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

WIP: SDK for writing cluster interceptors with built-in TLS support.
TODO

- [ ] User Docs
- [ ] Unit tests for server.go/main + 
- [ ] Refactoring TODOs

Replaces #1312 and #1042 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/retest

**Comment by dibyom** [comment]
>  detail: 'Try a different location, or try again later: Google Compute Engine does not have enough resources available to fulfill request: us-central1-b.'

**Comment by ilan-pinto** [comment]
@dibyom, anything I can do to assist?

**Comment by dibyom** [comment]
hi @ilan-pinto yes! this PR definitely needs some work. 

The high level goal is to simplify what it takes to write an interceptor - ideally users should be able to write an interceptor very easily in their own git repos without having to make it part of the triggers project itself. We would provide a library/sdk in pkg/interceptor that users could use for this.

A couple of examples where this could be used are in https://github.com/tektoncd/plumbing/tree/main/tekton/ci/cluster-interceptors

Today, this is somewhat possible:
1. one can implement the core interceptor logic by implementing the Interceptor interface ([example1](https://github.com/tektoncd/plumbing/blob/main/tekton/ci/cluster-interceptors/add-pr-body/pkg/pr.go), [example2](https://github.com/tektoncd/plumbing/blob/main/tekton/ci/cluster-interceptors/build-id/pkg/bid.go))

2. one can use [pkg/interceptor/server.Server](https://pkg.go.dev/github.com/tektoncd/triggers@v0.24.0/pkg/interceptors/server#Server) to implement the HTTP server ([example1](https://github.com/tektoncd/plumbing/blob/main/tekton/ci/cluster-interceptors/add-pr-body/cmd/interceptor/main.go), [example2](https://github.com/tektoncd/plumbing/blob/main/tekton/ci/cluster-interceptors/build-id/cmd/interceptor/main.go))
 
There are some issues with the second step above - while we have some of the common logic in pkg/interceptor/server, some of it is also in the core interceptor's main ([here](https://github.com/tektoncd/triggers/blob/main/cmd/interceptors/main.go)). So, today an interceptor author has to do a lot of boilerplate in order to write a server. Ideally most of this would be extracted away and interceptor authors can just call a server.Main or server.Start with a few options. I attempted to do this [here](https://github.com/tektoncd/triggers/pull/1403/files#diff-334499061ed3ebc4c0a86cfe6f72bce79f96de62bbf67e47ab90e46864166a58R220) and [here](https://github.com/tektoncd/triggers/pull/1403/files#diff-334499061ed3ebc4c0a86cfe6f72bce79f96de62bbf67e47ab90e46864166a58R43-R70). (The code is pretty old though so it may not be very relevant anymore).


So, I think what we need to do is:
- Extract as much as possible from https://github.com/tektoncd/triggers/blob/main/cmd/interceptors/main.go and make them reusable functions in pkg/interceptor/server

- Have a new helper function in the server package (server.Main, server.Run etc.) that does most of the boilerplate for the user. We'd need the author to pass in some options (e.g. timeouts etc.) but the goal would be to reduce the boilerplate as much as possible. 

(feel free to use this PR as a base or start fresh, whatever works best!)

**Pull request closed without merging**
