### PR TITLE
resources: Fail on non-string template labels.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Although ObjectMeta defines labels as a map[string]string, Unstructured
types allow for map[string]interface{}, which means that users can set
non-string values like ints in their configurations, and we will parse it
with no issues.

We discovered that the behavior of
[unstructured.GetLabels](https://github.com/kubernetes/apimachinery/blob/dd12c7a65e7f49c4e00b5bd5eb93de2fcbf7831d/pkg/apis/meta/v1/unstructured/unstructured.go#L395)
will silently ignore errors, returning an empty label set if a
non-string value is included. When used in triggers, this looks like we
are completely ignoring the user provided labels.

This change replaces GetLabels with it's underlying implementation, and bubbles
back the non-string error if it is encountered.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by dibyom** [comment]
Nice -- one thing I was thinking was that we could do a similar check in the resourceTemplate validation as well...so that if a user creates a resource with the wrong type, we catch it at creation time vs run time. What do you think?

/approve

**Comment by wlynch** [comment]
> Nice -- one thing I was thinking was that we could do a similar check in the resourceTemplate validation as well...so that if a user creates a resource with the wrong type, we catch it at creation time vs run time. What do you think?

That's probably going to be more work than I want to commit to for this PR. 😅 

TriggerResourceTemplates are currently stored as `runtime.RawExtension`s. We likely want to convert this to an `unstructured.Unstructured`, and I'm not sure what the scope of this change would entail (particularly in ensuring backwards compatibility). Alternatively, we'd could unmarshal the message in the webhook and in the controller, but that seems wasteful.

Worth noting - if we move forward with https://github.com/tektoncd/triggers/issues/697 this validation should happen automatically.

**Comment by dibyom** [comment]
Ahh, missed the runtime.RawExtension vs unstructured.Unstructured difference. I don't think it would be too bad converting them in the controller/webhook but I agree that is outside the scope of this PR.
/lgtm

**Pull request merged**
