### PR TITLE
Upgrade to latest knative.dev/pkg 1.9

### PR DESCRIPTION
**Pull request by khrm**
This update in knative improves the performance of the reconciler by eliminating a comparison in non-debug mode.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind misc

**Comment by savitaashture** [comment]
Pipeline PR ref : https://github.com/tektoncd/pipeline/pull/6256

**Review by savitaashture — APPROVED** [review]
:+1:

**Comment by khrm** [comment]
We should probably do v0.23.1 with this and MarshalJson fix.

**Review by dibyom — APPROVED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
/cherry-pick release-v0.23.x

**Pull request merged**
