### PR TITLE
Add SecurityContext to reconciled Deployment

### PR DESCRIPTION
**Pull request by MarcelMue**
# Changes

Adds a SecurityContext to the created Deployment - changes match those suggested here: https://github.com/tektoncd/triggers/issues/781

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
~- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)~
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Add a security context on event listener deployments to prevent issues with restrictive default PSPs.
```

### CODE REVIEW

**Comment by MarcelMue** [comment]
Sorry for the dumb questions but this is my first time contributing to tekton upstream:
1. Is this user facing? I would say yes because the behaviour does change slightly - not sure though.
2. CI is taking really long to run - is this expected or is something wrong with my PR?
3. I want to squash commits when I think changes are ready to merge - is that okay?

**Comment by dibyom** [comment]
Thanks for opening the PR @MarcelMue :)

> Is this user facing? I would say yes because the behaviour does change slightly - not sure though.

Yeah I'd agree. We should add a release note to the PR description like in https://github.com/tektoncd/triggers/pull/789

> CI is taking really long to run - is this expected or is something wrong with my PR?

It should take a few mins. Looks like its reporting that its still running after an hour. I'll retrigger the tests (I've seen this happen a few times before)

> I want to squash commits when I think changes are ready to merge - is that okay? 

Yes, that's ok!

**Comment by vdemeester** [comment]
@dibyom so… this breaks `OpenShift`. As this is user facing, I would have suggested to add a way to configure this behavior somehow (and disable it in some cases)

**Comment by MarcelMue** [comment]
> @dibyom so… this breaks `OpenShift`. As this is user facing, I would have suggested to add a way to configure this behavior somehow (and disable it in some cases)

Interesting - can you elaborate to me how it breaks `OpenShift` (I have never worked with it)?

I assumed this was safe because it is on master `yaml`s without being configurable - e.g.:
https://github.com/tektoncd/triggers/blob/0a9df14bf5731468e5cfc49d065a41cebfe82de6/config/controller.yaml#L78-L81

**Comment by vdemeester** [comment]
Hey @MarcelMue, more detail in #864, but in a gist, OpenShift needs some "extra rights" to be able to set a given uid to a Pod. By default, OpenShift does use a random uid, and it works just fine for the eventlistener pods. This changes forces to attach to the eventlistener pod a serviceAccount with `anyuid` — which adds a little bit of burden to *operators* of tektoncd/triggers instances (and even more to the user if one wants to add its own ServiceAccount if that's possible).

**Comment by vdemeester** [comment]
> I assumed this was safe because it is on master `yaml`s without being configurable - e.g.:
> https://github.com/tektoncd/triggers/blob/0a9df14bf5731468e5cfc49d065a41cebfe82de6/config/controller.yaml#L78-L81

Indeed 😉 This is another *small* problem that we may have, but when we package Tekton for OpenShift, we do control the payload that we apply and thus we can safely remove that part (`runAsUser`) — but we do not control the code that is in `tektoncd/triggers`, so there is no easy way to remove the `runAsUser` set by the code in that PR.

@MarcelMue note that, I am 100% for this change in standard k8s. We just need to find a way to disable this behavior on demand (but having it enabled by default in a standard distribution of tektoncd).

**Comment by dbazhal** [comment]
definately it broken our triggers in openshift with "unable to validate against any security context constraint: [spec.containers[0].securityContext.runAsUser: Invalid value: 65532: must be in the ranges: [1000750000, 1000759999]]"

**Pull request merged**
