### PR TITLE
Update to go 1.17.8

### LINKED ISSUE #1335: Update to golang 1.17.8
From @afrittoli:
 heads-up that the golang 1.17.8 CI images are available now - we went through the update in pipeline and you may want to do the same on triggers side since it it required to update to the latest knative/pkg https://github.com/tektoncd/pipeline/pull/4712 and good to have in any case

This was the pipeline PR required to fix gofmt and related changes https://github.com/tektoncd/pipeline/pull/4714

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

As part of this, I also ran `go fmt -s -w cmd/ pkg/ test/ tekton/` to fix the
build tags and then ran `./hack/update-codegen.sh` to regenerate the code.

Fixes #1335

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Triggers is now built using go 1.17.8
```

### CODE REVIEW

**Comment by dibyom** [comment]
> >> go version
go version go1.16.13 linux/amd64


Looks like we need to change something else too

**Comment by dibyom** [comment]
Should be ready for a review now @khrm @savitaashture

**Review by khrm — APPROVED** [review]
/lgtm

**Pull request merged**
