### PR TITLE
Add additional documentation.

### PR DESCRIPTION
**Pull request by bigkevmcd**
# Changes

Adds additional documentation for the CEL interceptor.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Improved documentation for CEL interceptor overlays
```

### CODE REVIEW

**Comment by bigkevmcd** [comment]
This is failing, but I can't really see why.

```
I0310 18:06:14.886] --------------------------------
I0310 18:06:14.887] ---- Linting the yaml files ----
I0310 18:06:14.887] --------------------------------
I0310 18:09:08.970] level=error msg="Timeout exceeded: try increase it by passing --timeout option"
I0310 18:09:09.187] Diffing against the documentation yaml
I0310 18:09:09.481] ============================
I0310 18:09:09.482] ==== BUILD TESTS FAILED ====
I0310 18:09:09.483] ============================
W0310 18:09:09.584] Run: ('/workspace/./test-infra/jenkins/../scenarios/../hack/coalesce.py',)
E0310 18:09:09.690] Command failed
I0310 18:09:09.691] process 473 exited with code 1 after 3.0m
```

**Comment by dibyom** [comment]
@bigkevmcd I've noticed some flakiness in our build tests especially when the commits contain markdown files :(

**Pull request merged**
