### PR TITLE
Respond appropriately to CloudEvent requests

### PR DESCRIPTION
**Pull request by bigkevmcd**
# Changes
This changes the behaviour of the triggers Sink to respond to CloudEvents with a CloudEvent response.

Previously the code always responded with a standard HTTP application/json response, which could cause issues for CloudEvents clients leading to errors and possibly retries.

The handler detects CloudEvent requests and responds with the same body in response.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
CloudEvents sent to a Trigger will now receive a valid CloudEvent response.
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by dibyom** [comment]
> One issue that I'm not sure about, is https://github.com/tektoncd/triggers/pull/1469/files#diff-040df62660d4581f9d1f6c27bebee01870d8b7b0cda5c21803369f5a55106e09R226
> Previously, it didn't return after sending the failed responses, which the other error cases did, there's no obvious reason why?

That looks like a bug but one that we'd probably never encounter since we were always returning valid json response back

**Comment by dibyom** [comment]
Thank you @bigkevmcd - One thing I'd add is some documentation in to document this feature https://github.com/tektoncd/triggers/blob/main/docs/eventlisteners.md#understanding-eventlistener-response

**Comment by bigkevmcd** [comment]
I've added an example response for CloudEvents, and added a Type and improved the `Source` field to include the namespace.

**Comment by dibyom** [comment]
Hmm - the issue with the test seems to be that we are creating GKE clusters version 1.22 while trying to install the latest pipelines v0.41 which requires K8s 1.23

**Pull request merged**
