### PR TITLE
Update Cel-Go to v0.16.0

### LINKED ISSUE #1612: Make all cel extensions available
### Feature request

The documentation (https://tekton.dev/docs/triggers/cel_expressions/#cel-go-extensions) says that all extensions at https://github.com/google/cel-go/tree/master/ext are available for use.
@ggallen tried to use sets.contains without luck.

### PR DESCRIPTION
**Pull request by khrm**
This introduces some new extension functions like `set.contains`, etc.
Fixes #1612 

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind misc
/test pull-tekton-triggers-integration-tests

**Comment by bigkevmcd** [comment]
Looks good to me!

**Review by dibyom — APPROVED** [review]

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
