### PR TITLE
Fix different uid generated in one triggerTemplate

### PR DESCRIPTION
**Pull request by cccfeng**
When different uid generated in one triggerTemplate, internal references will fail.

For example, code examples in [doc](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md#triggertemplates) also fail to run.

```
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineResource
    metadata:
      name: git-source-$(uid)
    spec:
      type: git
      params:
      - name: revision
        value: $(params.gitrevision)
      - name: url
        value: $(params.gitrepositoryurl)
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: simple-pipeline-run
    spec:
      pipelineRef:
        name: simple-pipeline
      params:
      - name: message
        value: $(params.message)
      - name: contenttype
        value: $(params.contenttype)
      resources:
      - name: git-source
        resourceRef:
          name: git-source-$(uid)
```
I found `git-source-5ls8v` in generated and error info shows
```
PipelineRun tekton-pipelines/simple-pipeline-runwfxxq can't be Run; it tries to bind Resources that don't exist: Error following resource reference for code-repo: pipelineresource.tekton.dev "git-source-vddbg" not found.  
```

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by dibyom** [comment]
Thanks @cccfeng Good catch! Normally I'd recommend adding a targeted test case for this but I did a bunch of refactoring for these tests over so I can add it myself :angel: 

https://github.com/tektoncd/triggers/compare/master...dibyom:tests?expand=1

**Comment by cccfeng** [comment]
> Thanks @cccfeng Good catch! Normally I'd recommend adding a targeted test case for this but I did a bunch of refactoring for these tests over so I can add it myself 👼
> 
> https://github.com/tektoncd/triggers/compare/master...dibyom:tests?expand=1

Ha ha, I'm lucky to be lazy this time. I saw that one test case of the method is to generate uid twice, so I changed it there only.

**Pull request merged**
