### PR TITLE
Fixed link in EventListener secure connection docs

### PR DESCRIPTION
**Pull request by siamaksade**
# Changes

The broken link to the example for EventListener secure connection in docs is fixed
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes
- Link fixed in the docs for the EventListener example with secure connection

### CODE REVIEW

**Comment by savitaashture** [comment]
@siamaksade could you add `Release Notes` section above

**Comment by bigkevmcd** [comment]
/lgtm

Trivial change.

**Pull request merged**
