### PR TITLE
Update Readme.md - correcting minor typo

### PR DESCRIPTION
**Pull request by dibyom**
Added missing word, "can used" should read "can be used..."

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by dibyom** [comment]
@anneqm since this is your first contribution, you'll have to sign the CLA: https://cla.developers.google.com/

**Comment by anneqm** [comment]
@dibyom thank you!  I am now covered under the IBM CLA.

**Comment by vdemeester** [comment]
@anneqm I think you need to comment `@googlebot I fixed it` for the cla check to retry :angel:

**Comment by anneqm** [comment]
@googlebot I fixed it

**Comment by anneqm** [comment]
@googlebot I fixed it

**Comment by ncskier** [comment]
@anneqm does the comment need a period?
@googlebot I fixed it.

**Comment by dibyom** [comment]
I think the bot is working but the problem is the email associated with the commit i.e. `54442260+anneqm@users.noreply.github.com` 

I think rebasing the commit email with the one that the CLA was signed with should help: https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit/28845565

**Comment by anneqm** [comment]
@googlebot I fixed it.

**Pull request closed without merging**
