### PR TITLE
Remove deprecated fields podTemplate and serviceType

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes
Issue: https://github.com/tektoncd/triggers/issues/849

Removed deprecated fields podTemplate and serviceType from eventlistener spec

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

`podTemplate` and `serviceType` from eventlistener spec has been deprecated in previous release (0.9.0) and now as part of this release (0.11.0) those fields will be removed completely
so usage of `podTemplate` and `serviceType` is something like below

```release-note
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  triggers:
    ...
  resources:
    kubernetesResource:
      serviceType: NodePort
      spec:
        template:
          metadata:
            labels:
              key: "value"
            annotations:
              key: "value"
          spec:
            serviceAccountName: tekton-triggers-github-sa
            nodeSelector:
              app: test
            tolerations:
              - key: key
                value: value
                operator: Equal
                effect: NoSchedule
```

### CODE REVIEW

**Comment by dibyom** [comment]
Can we update the Release notes to mention that the fields have been deleted?

**Comment by savitaashture** [comment]
> Can we update the Release notes to mention that the fields have been deleted?

Done :+1:

**Pull request merged**
