### PR TITLE
Add @wlynch as an OWNER ⚡

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

@wlynch has been active on the Triggers project for a while now adding a bunch of
features - multiple bindings, interceptors, ongoing work on go modules etc. He has
also reviewed 42 PRs and meets the OWNERS requirements!
https://tekton.devstats.cd.foundation/d/46/pr-reviews-by-contributor?orgId=1&from=1563041702101&to=1578942902101&var-period=q&var-repo_name=tektoncd%2Ftriggers&var-reviewers=%22wlynch%22

/cc @bobcatfish @dlorenc @iancoffey @ncskier @vtereso 

/hold

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
:+1: from me! Thanks for your hard work @wlynch  :D

**Comment by dibyom** [comment]
I think @dlorenc is OOO for a bit but we have everyone else's approval so I'm going to 
/approve

**Pull request merged**
