### PR TITLE
Cleanup cluster resources when test fails

### LINKED ISSUE #495: Cleanup cluster resources when e2e tests fail
# Expected Behavior
I should be able to re-run the e2e test on the same cluster twice even if the first run fails

# Actual Behavior
When e2e tests fail, cluster resources "my-clustertriggerbinding", "my-role", "my-rolebinding" are not cleaned up.  So, if I re-run the test it always fails

# Steps to Reproduce the Problem
1. Run e2e tests:  go test -v -count=2 -tags=e2e -timeout=20m ./test

# Additional Info

To fix:
1. Extract cluster trigger binding out into its own test
2. Add teardown methods for each cluster resource created.

/area testing

### PR DESCRIPTION
**Pull request by dibyom**
Fixes #495

Signed-off-by: Dibyo Mukherjee <dibyo@google.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by ncskier** [comment]
I tested this out (using Docker for Desktop) and it didn't seem to clean up the cluster-wide resources when I interrupted the test with Ctrl+C or when I added a `t.Fatal()`to make the test fail 😕I'm not sure why though... did it work for you when you tested this @dibyom ?

**Comment by ncskier** [comment]
Hm, I just tested again, and the cleanup worked when I put a `t.Fatal()` in the test. However, the cleanup still doesn't seem to work when I interrupt the test with Ctrl+C.

**Comment by dibyom** [comment]
The cleanup should work  Ctrl + C as well due to 
`knativetest.CleanupOnInterrupt(func() { cleanup(t, c, namespace) }, t.Logf)`

Just tried this out on my local environment (linux machines, cluster is GKE) and the test cleaned up fine
`

**Comment by ncskier** [comment]
Ok. Yeah, not sure why the Ctrl+C isn't working for me, but at least it cleans up when the test fails. So, this PR definitely addresses the issue 👍
/lgtm
/approve

**Pull request merged**
