### PR TITLE
Add 2020 roadmap 🛣️

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

In tektoncd/community#77 we started on a roadmap
for 2020 for all of Tekton but folks pointed out it makes more sense to
let each project's own roadmap live in the repo with them.

(Also included a TOC in the main README)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by dibyom** [comment]
/approve

cc @ncskier

**Comment by ncskier** [comment]
👍 
/approve

**Comment by ncskier** [comment]
Do we want more owners to look this over, or are we good to merge it?

**Comment by dibyom** [comment]
Let's merge as is and discuss any edits in a WG
/lgtm

**Pull request merged**
