### PR TITLE
Update CEL-GO to v0.20.1

### PR DESCRIPTION
**Pull request by khrm**
# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind misc

**Review by savitaashture — APPROVED** [review]

**Comment by khrm** [comment]
Fixes: https://github.com/tektoncd/triggers/pull/1718

**Comment by khrm** [comment]
Sure. I would add. Thanks. It seems we miss this from earlier updates also.

**Comment by khrm** [comment]
@bigkevmcd @savitaashture I am raising another PR. Let's add this PR for version updates and cut the release.

**Comment by savitaashture** [comment]
> @bigkevmcd @savitaashture I am raising another PR. Let's add this PR for version updates and cut the release.

Sure
@khrm can you create an issue to track the same

**Comment by khrm** [comment]
So this PR got closed because I rebase and push. There was no difference.

**Comment by bigkevmcd** [comment]
@khrm Do you want me to do this work?

**Comment by khrm** [comment]
Sure. You can take this up. I was focussing on results first.

**Pull request closed without merging**
