### PR TITLE
Update CEL GO to v0.9.0 and CEL Spec to v0.6.0

### PR DESCRIPTION
**Pull request by khrm**
Update CEL GO to v0.9.0 for fixing bugs and improving cel performance.
https://github.com/google/cel-go/releases/tag/v0.9.0
https://github.com/google/cel-go/releases/tag/v0.8.0

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Comment by dibyom** [comment]
Any breaking changes in CEL to be aware of? Also, can we call this out in the release notes section?

**Comment by TristonianJones** [comment]
There have been some substantial improvements and changes to CEL even since 0.9.0. I was about to publish the following pull request and saw this one:
https://github.com/tektoncd/triggers/compare/main...TristonianJones:cel-upgrade

**Pull request merged**
