### PR TITLE
Fix broken anchor link in EventListener docs

### PR DESCRIPTION
**Pull request by tragiclifestories**
# Changes

Just a trivial documentation fix - there's a broken link in the EventListener docs ToC - this change will properly link to the interceptors section down below.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

I don't think this is relevant but will fill out if maintainers disagree. I'm also happy to write a longer commit message but I think the change is pretty transparent ...

### CODE REVIEW

**Comment by tragiclifestories** [comment]
(Just trying to sort out the CLA with work ... )

**Comment by ncskier** [comment]
Once you sign the CLA, it _should_ pass the test if you leave a comment saying `@googlebot I signed it!` 👍 
/ok-to-test

**Comment by tragiclifestories** [comment]
@googlebot I signed it!

**Comment by tragiclifestories** [comment]
thanks @ncskier - sorry about the delay, was figuring out the CLA business with my company but sorted now.

**Comment by ncskier** [comment]
No worries; I'm glad you got it sorted out. Thanks for the PR! 🙂 
/lgtm
/approve

**Comment by ncskier** [comment]
Following the [tekton plumbing Slack](https://tektoncd.slack.com/archives/CJ4ERJWAU), something's up with the tests 😅

**Comment by tragiclifestories** [comment]
OK, I'm out of ideas. Will keep an eye on the slack ...

**Pull request merged**
