### PR TITLE
add logging config to EventListener binary

### PR DESCRIPTION
**Pull request by akihikokuroda**
# Changes
This PR for the issue https://github.com/tektoncd/triggers/issues/76

The logging config is in config-logging.yaml file.  The log component string is `eventlistener`  and the default setting is `info`.  The Logger is set in the sink.Resource so that any member function of the struct can use the logger.
 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by ncskier** [comment]
Thanks for the PR @akihikokuroda! Before looking through the code, I went to try it out, and my EventListener, which I created in the `default` namespace, failed to start up:
```
Warning  FailedMount  35s (x8 over 99s)  kubelet, docker-desktop  MountVolume.SetUp failed for volume "config-logging" : configmap "config-logging-triggers" not found
```
I think that this is happening because the `config-logging-triggers` ConfigMap is in the `tekton-pipelines` namespace, and my EventListener pod is in the `default` namespace... so either we have to find a way to get the ConfigMap from the `tekton-pipelines` namespace, or pass the logging configuration to the EventListener in a different way.

**Comment by akihikokuroda** [comment]
I included the update of eventlistener.md in this PR.  I added a statement that the config map must be defined in the same namespace as the eventlistner.

**Comment by akihikokuroda** [comment]
@googlebot I fixed it.

**Comment by akihikokuroda** [comment]
New PR is created with the same changes.
https://github.com/tektoncd/triggers/pull/204

**Pull request closed without merging**
