### PR TITLE
Add AzureRepo push and pull request examples

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes
* Added tigger binding examples to show how AzureRepo push and pullrequest works

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/triggers/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
Added sample examples for AzureRepo
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by dibyom** [comment]
Also - since this example has two sub-folders within one example folder, will the e2e-yaml test work properly?

**Comment by savitaashture** [comment]
> Also - since this example has two sub-folders within one example folder, will the e2e-yaml test work properly?
> 
> I looked at the integration test logs but did not see any of the azurerepo examples applied: https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_triggers/1419/pull-tekton-triggers-integration-tests/1559217221694132224#1:build-log.txt%3A2

e2e-test is not running because this is sample examples to show how triggerbinding  for azure repo looks like something similar to [cloudevent](https://github.com/tektoncd/triggers/tree/main/examples/v1beta1/cloudevent), [eventlistener-tls-connection](https://github.com/tektoncd/triggers/tree/main/examples/v1beta1/eventlistener-tls-connection)

**Review by khrm — COMMENTED** [review]
Ideally, this example should go to catalog but we aren't using catalog for TriggerBindings yet.

**Comment by dibyom** [comment]
> e2e-test is not running because this is sample examples to show how triggerbinding for azure repo looks like something similar to [cloudevent](https://github.com/tektoncd/triggers/tree/main/examples/v1beta1/cloudevent), [eventlistener-tls-connection](https://github.com/tektoncd/triggers/tree/main/examples/v1beta1/eventlistener-tls-connection)

I see, we are just running examples for a few folders

/approve

**Pull request merged**
