### PR TITLE
Update title fields in docs/README.md (release-v0.12.x patch)

### PR DESCRIPTION
**Pull request by eliasnorrby**
:information_source: This PR targets a release branch, not `main`.

# Changes

Patch a previous release branch with the changes introduced in #1095, i.e:

Use more appropriate values for the title fields in the frontmatter of README.md. In the context of the sidebar navigation of the website, for example, 'Overview' is too generic.

See #1095 and tektoncd/website#270 for more background.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [:no_good_man:] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#tests) (if functionality changed/added)
- [:no_good_man:] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#docs) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commits)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by dibyom** [comment]
Hmm....not sure why the build tests are trying to run gocritic when no go files have been changed.

**Comment by eliasnorrby** [comment]
Yeah... seems the `defaullt_build_test_runner` will run `gofmt` [no matter what](https://github.com/tektoncd/plumbing/blob/96d52ed42bea91cf3d9eae630bd7b5f0017a4ef4/scripts/presubmit-tests.sh#L180-L188)?

But I can port d8e21ea to this branch either way.

**Comment by dibyom** [comment]
hi @eliasnorrby it looks like we'll have to add in https://github.com/tektoncd/triggers/commit/da36a41042584305ecfe181caaba77ca60eda945 as well to this branch for the integration tests to work. Sorry about the extra work!

**Comment by eliasnorrby** [comment]
> hi @eliasnorrby it looks like we'll have to add in [da36a41](https://github.com/tektoncd/triggers/commit/da36a41042584305ecfe181caaba77ca60eda945) as well to this branch for the integration tests to work. Sorry about the extra work!

No worries! I tried applying da36a41 as cleanly as possible, but I'm no go developer, so I'm resorting to common sense when resolving conflicts in `go.mod` etc. 

Integration tests are passing, but build tests are failing with this:
> /home/prow/go/src/github.com/tektoncd/triggers is out of date. Please run hack/update-codegen.sh

---

Oh, wait, I just realized I can't cherry-pick da36a41 as is, because it updates a dependency and includes patches to generated files, and in the context of this branch, we're upgrading from another version of the dependency, so the diff of generated files will be different. Right?

Is this the right way to apply da36a41:
1. Cherry-pick it
2. Resolve conflicts, keeping only updates to `go.mod`
2. Run `hack/update-codegen.sh`
3. Commit
4. Profit?

I'm giving it a try :man_shrugging:

**Comment by dibyom** [comment]
Almost there - You need to run `hack/update-codegen.sh`  (I think just running `go mod vendor` will also work)

I ran it and then the build tests passed for me locally!

**Comment by eliasnorrby** [comment]
Okay, so I spent a good 2 hours troubleshooting this. Thing is, I already ran `hack/update-codegen.sh`, and tests were passing locally for me as well. I did this long write-up, going into how something must be awry in the CI environment, because it's complaining I'm lacking two files, but I can see them on disk. It was only when I went to get a GitHub link to them that I discovered the culprit: [a global gitignore entry](https://github.com/eliasnorrby/dotfiles/blob/8f534fb43b855e9d21616c22653ef3427865f52c/shell/git/ignore#L33). So the files were generated, but not committed nor pushed. :man_facepalming: 

With it [forcefully removed](https://github.com/eliasnorrby/dotfiles/commit/1ac881da309151354340d5021af63d0f391eb62c) and the missing files added, tests are passing.

TIL: `git check-ignore -v`

**Comment by dibyom** [comment]
Ahh nice sleuthing! I've definitely been bitten by global gitignores in the past too!

/approve
/lgtm

**Comment by eliasnorrby** [comment]
@dibyom, while we're at it, would you be able to push a `release-v0.13.x` branch to 6ea31d92 (i.e. tag `v0.13.0`)? That would allow me to patch the `v0.13.0` release for tektoncd/website#270.

**Pull request merged**
